resources:
  repositories:
    - repository: buildTemplates
      type: github
      name: greenmooseSE/Gmd.Tools.AzureDO.BuildTemplates.PushBucket
      ref: 'refs/heads/feat/ab#477-crossOrgGitSubmodules'
      endpoint: greenmooseSE

parameters:
  - name: paramDoCleanCheckout
    displayName: Clean checkout.
    type: boolean
    default: false

trigger:
  branches:
    include:
      - "*"
    exclude:
      - "master"
  paths:
    include:
    - base-npm-app/*
    
name: 0.0.0-TBD_$(Date:yyyyMMdd)$(Rev:.r)

extends:
  template: templates/base-npm-app.yaml@buildTemplates
  parameters:
    paramDoCleanCheckout: ${{ parameters.paramDoCleanCheckout }}
    paramTemplatesRepoName: buildTemplates
    paramWorkingDirectory: base-npm-app
