resources:
  repositories:
    - repository: buildTemplates
      type: github
      name: greenmooseSE/Gmd.Tools.AzureDO.BuildTemplates
      ref: 'refs/heads/feat/ab#351-cdCiForNextJsApp'
      endpoint: greenmooseSE

parameters:
  - name: paramDoCleanCheckout
    displayName: Clean checkout.
    type: boolean
    default: false

trigger:
  branches:
    include:
      - "*"
    exclude:
      - "master"
  paths:
    include:
    - base-npm-app/*
    exclude:
    - '**/cd-*.yaml'
    
name: $(BuildName)$(Rev:rr)

extends:
  template: templates/base-ci-node.yaml@buildTemplates
  parameters:
    paramDoCleanCheckout: ${{ parameters.paramDoCleanCheckout }}
    paramTemplatesRepoName: buildTemplates
    paramWorkingDirectory: base-npm-app
    paramNodeAppType: general
