resources:
  repositories:
    - repository: buildTemplates
      type: github
      name: greenmooseSE/Gmd.Tools.AzureDO.BuildTemplates.PushBucket
      ref: 'refs/heads/feat/ab#503-ciCdStrategyPs'
      endpoint: greenmooseSE

parameters:
  - name: paramBuildNameToDeployToDev
    displayName: Deploy to Dev, a specific CI build as identified by its build number.
    type: string
    default: " "
  - name: paramDeployProd
    displayName: Deploy specified rc-tag to production.
    type: boolean
    default: false


pr: none
trigger:
  branches:
    exclude:
    - '*'
  tags:
    include:
    - 'rc-*'
  paths:
    exclude:
      - ci-*.yaml
    
# name: $(BuildNameBeforeTimestamp)$(Date:yyyyMMdd\THHmm)$(Rev:rr)
name: $(BuildName)$(Rev:+rr)

extends:
  template: templates/base-cd.yaml@buildTemplates
  parameters:
    paramTemplatesRepoName: buildTemplates
    paramDeploymentType: none
    # paramEnvVarsForTestTask:
    #   AzDoApiPAT_Tests: $(AzDoApiPAT_Tests)
    paramBuildNameToDeployToDev: ${{ parameters.paramBuildNameToDeployToDev }}
    paramDeployProd: ${{ parameters.paramDeployProd }}
    paramPipelineDefinitionId: 79
    paramCiHasArtifacts: false
