resources:
  repositories:
    - repository: buildTemplates
      type: github
      name: greenmooseSE/Gmd.Tools.AzureDO.BuildTemplates.PushBucket
      ref: 'refs/heads/feat/ab#351-cdCiForNextJsApp'
      endpoint: greenmooseSE

parameters:
  - name: paramDoCleanCheckout
    displayName: Clean checkout.
    type: boolean
    default: false

trigger:
  branches:
    include:
      - "*"
    exclude:
      - "master"
  paths:
    include:
    - base-nextjs-web/*
    
name: $(BuildName)$(Rev:rr)

extends:
  template: templates/base-ci-web-nextjs.yaml@buildTemplates
  parameters:
    paramDoCleanCheckout: ${{ parameters.paramDoCleanCheckout }}
    paramTemplatesRepoName: buildTemplates
    paramWorkingDirectory: base-nextjs-web
    paramEnvVarsForTestTask:
      EnvKey1: EnvVal1
