resources:
  repositories:
    - repository: buildTemplates
      type: github
      name: greenmooseSE/Gmd.Tools.AzureDO.BuildTemplates
      ref: "refs/heads/release/0.0"
      endpoint: greenmooseSE

parameters:
  - name: paramDoCleanCheckout
    displayName: Clean checkout.
    type: boolean
    default: false

trigger:
  branches:
    include:
      - refs/heads/feat/*
      - refs/heads/bug/*
      - refs/heads/release/*
    # exclude:
    #   - "master"

  # To avoid all apps in this multi-repo to trigger upon rc-tags, we only allow manual trigger for tags.
  # tags:
  #   include:
  #     - rc-*

  #Note that paths are not considered for tags per se, but we keep to see if it works with using tags in branches filter instead. See https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#tags
  paths:
    include:
      - ps-lib/*
    exclude:
      - "**/cd-*.yaml"

name: $(BuildName)$(Rev:rr)

extends:
  template: templates/base-ci-ps-lib.yaml@buildTemplates
  parameters:
    paramDoCleanCheckout: ${{ parameters.paramDoCleanCheckout }}
    paramTemplatesRepoName: buildTemplates
    paramWorkingDirectory: ps-lib
    paramEnvVarsForTestTask:
      EnvKey1: EnvVal1
